"""add_detection_to_flights_upload

Revision ID: 31ede33a6483
Revises: ca5cb095c123
Create Date: 2026-05-30 22:53:56.403625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ede33a6483'
down_revision: Union[str, Sequence[str], None] = 'ca5cb095c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('flight_id', sa.UUID(), nullable=True))
    op.add_column('detections', sa.Column('bbox_x1', sa.Float(), nullable=False))
    op.add_column('detections', sa.Column('bbox_y1', sa.Float(), nullable=False))
    op.add_column('detections', sa.Column('bbox_x2', sa.Float(), nullable=False))
    op.add_column('detections', sa.Column('bbox_y2', sa.Float(), nullable=False))
    op.add_column('detections', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('detections', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'detections', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'detections', 'drone_flight_logs', ['flight_id'], ['flight_id'])
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_column('detections', 'user_id')
    op.drop_column('detections', 'image_url')
    op.drop_column('detections', 'longitude')
    op.drop_column('detections', 'latitude')
    op.drop_column('detections', 'bbox_y2')
    op.drop_column('detections', 'bbox_x2')
    op.drop_column('detections', 'bbox_y1')
    op.drop_column('detections', 'bbox_x1')
    op.drop_column('detections', 'flight_id')
    # ### end Alembic commands ###
