"""Added image_id to detections; Added relations to Image and Detections

Revision ID: 3fe8e49d3530
Revises: 697e0a8e314b
Create Date: 2026-09-26 00:56:19.924578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe8e49d3530'
down_revision: Union[str, Sequence[str], None] = '697e0a8e314b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'detections', 'images', ['image_id'], ['image_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_column('detections', 'image_id')
    # ### end Alembic commands ###
