"""create_initial_schema

Revision ID: 4185ec55f706
Revises: 
Create Date: 2026-04-14 20:31:49.773833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4185ec55f706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(), nullable=False),
    sa.Column('boundary_coordinates', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('drone_flight_logs',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('pilot_name', sa.String(), nullable=False),
    sa.Column('area_covered', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('trash_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('flight_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['drone_flight_logs.flight_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('detections',
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('images')
    op.drop_table('trash_logs')
    op.drop_table('reports')
    op.drop_table('drone_flight_logs')
    op.drop_table('users')
    op.drop_table('areas')
    # ### end Alembic commands ###
