"""updated_schema_for_flutter

Revision ID: 61645b3d62c3
Revises: 4185ec55f706
Create Date: 2026-04-21 00:21:25.166956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61645b3d62c3'
down_revision: Union[str, Sequence[str], None] = '4185ec55f706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('center_latitude', sa.Float(), nullable=True))
    op.add_column('areas', sa.Column('center_longitude', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('is_manual', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'description')
    op.drop_column('reports', 'location_name')
    op.drop_column('detections', 'is_manual')
    op.drop_column('areas', 'center_longitude')
    op.drop_column('areas', 'center_latitude')
    # ### end Alembic commands ###
