"""Add is critical in reports

Revision ID: ed2aed22dd46
Revises: 31ede33a6483
Create Date: 2026-06-01 04:45:35.595811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2aed22dd46'
down_revision: Union[str, Sequence[str], None] = '31ede33a6483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('is_critical', sa.Boolean(), nullable=True))
    op.execute("""
            UPDATE reports 
            SET is_critical = FALSE 
            WHERE is_critical IS NULL;""")  
    op.alter_column('reports', 'is_critical', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'is_critical')
    # ### end Alembic commands ###
